// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GateFilterController from "./gate_filter_controller"
application.register("gate-filter", GateFilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SlimSelectController from "./slim_select_controller"
application.register("slim-select", SlimSelectController)
